version: '3'
services:
  backend:
    build: ./
    ports:
      - 3001:3001
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - 80:80
